version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC endpoint for receiving OTLP traces
      - "14268:14268"  # Jaeger HTTP endpoint
      - "9411:9411"    # Zipkin compatibility endpoint
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"  # OpenTelemetry gRPC endpoint
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
