receivers:
  otlp:
    protocols:
      grpc:  # Enable gRPC receiver on port 4317
        endpoint: "0.0.0.0:4317"

exporters:
  otlp:
    endpoint: "jaeger:4317"  # Send data to Jaeger gRPC endpoint
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
